name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'   # ✅ Fixed version (use 3.10 or 3.11)

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          elif [ -f "requirement.txt" ]; then
            pip install -r requirement.txt
          else
            echo "⚠️ No requirements.txt or requirement.txt found — skipping install"
          fi

      - name: Verify Streamlit installation (smoke test)
        run: |
          python -m streamlit --version || echo "⚠️ Streamlit not installed"

      - name: Lint with flake8 (optional)
        run: |
          pip install flake8
          flake8 . || echo "⚠️ Lint warnings (not failing build)"

      - name: Run tests
        run: |
          if command -v pytest >/dev/null 2>&1 && [ -d "tests" ]; then
            pytest -q
          elif [ -f "test.py" ]; then
            python test.py
          else
            echo "⚠️ No tests found — skipping"
          fi
